### ISSUE TITLE
Problem admin drop-down menu

### ISSUE THREAD

**Issue by pedroao** [nakome/morfy-admin-panel#52]
Ola, que passa amigo 
Sorry about last time. Problems in my net.
I fund litter bug on admin plugin.
It is on file: partials/navigation.html
On line:
12<img  class="user-logo" src="<?php echo $grav_url; ?>" alt="" />
13  <span class="user-email"><?php echo $email;?></span>
the problem when I have gravatar account the drop-down menu is not showing proper.
Showing photo and email.
I just remove the line 13 and work ok.

**Comment by xxwebplus** [comment]
Hi pedroao,
please download the latest version admin panel bootstrap ;)
